Add initial version for FTN credential blog.
findy-network/findy-network.github.io pull request #62
Opened 2022-04-28 13:30 UTC by lauravuo-techlab

2022-04-29 07:43 UTC, techlab-lainio requested changes
I liked the language and rhythm in this post very much! Some comments I hope to help. Let's discuss these if needed.

2022-04-29 07:43 UTC, techlab-lainio commented on content/en/blog/trust-in-your-wallet/index.md
> +the user's name and personal identification code. Often users authenticate using their bank ID.
Last paragraph.. should be say: usually users use their banks as IdPs or something. When I think how difficult those who don't know Finnish system (TUPAS) is to understand this part, I think it needs clarification.

2022-04-29 07:43 UTC, techlab-lainio commented on content/en/blog/trust-in-your-wallet/index.md
> +The selective disclosure feature would allow users to share only
should we have a link for 'selective disclosure'?

2022-04-29 07:43 UTC, techlab-lainio commented on content/en/blog/trust-in-your-wallet/index.md
> +In this FTN issuer demo, we utilized the OIDC protocol again but now used it as
'used it as the credential data source' in bold?

2022-04-29 07:43 UTC, techlab-lainio commented on content/en/blog/trust-in-your-wallet/index.md
> +integration point - and for that, the SSI agent provides the needed functionality.
'ajatusviiva' should be the very long one without spaces at the ends?

2022-04-29 07:43 UTC, techlab-lainio commented on content/en/blog/trust-in-your-wallet/index.md
> +and the FTN service at <http://localhost:8081>.
Should there be the last paragraph: 'In case you have any questions or are interested in building your own OIDC-SSI bridge, please contact your team. Contact info can be found from <url>' or something?

2022-04-29 07:43 UTC, techlab-lainio commented on content/en/blog/trust-in-your-wallet/index.md
> +## Food for Thought: Self-service Issuers
In the following three chapters, their style isn't as easy to read as it was at the beginning of the post. Maybe shorten the sentences or something. The points are excellent.

2022-05-02 08:54 UTC, lauravuo-techlab commented
Thanks @techlab-lainio for the excellent comments!

2022-05-02 08:55 UTC, merged